### PR TITLE
Frame proto

### PR DESCRIPTION
**Pull request by CodyRoberson**
Created the basic structure of the GUI and integrated DrawPanelOne and DrawPanelTwo into DrawFrame.

### CODE REVIEW

**Comment by CodyRoberson** [comment]
Please review and Comment on the code/design.
Execute code from the driver class.
This version is run-able.

**Comment by CodyRoberson** [comment]
image
Run Test Image

**Comment by andrewdurkiewicz** [comment]
I like it!

**Comment by andrewdurkiewicz** [comment]
@CodyRoberson Did we get this integrated with the rest of the objects? Tonight I am going to do a test case with the circle shape. If this works, we should be finishing up quickly tomorrow night.

**Pull request merged**
